# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcuser', models.CharField(max_length=32, verbose_name='使用者')),
                ('ip', models.CharField(max_length=32, verbose_name='IP地址')),
                ('mac', models.CharField(blank=True, max_length=32, null=True, verbose_name='MAC地址')),
                ('cpu', models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU信息')),
                ('disk', models.CharField(blank=True, max_length=32, null=True, verbose_name='硬盘')),
                ('memory', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存')),
                ('display', models.CharField(blank=True, max_length=32, null=True, verbose_name='显示器')),
                ('department', models.CharField(blank=True, max_length=32, null=True, verbose_name='部门')),
                ('note', models.CharField(blank=True, max_length=32, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'PC',
                'verbose_name_plural': 'PC',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='ip地址')),
                ('port', models.CharField(max_length=16, verbose_name='端口')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('status', models.CharField(blank=True, max_length=32, null=True, verbose_name='连接状态')),
                ('sys_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统类型')),
                ('sys_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统版本')),
                ('cpu', models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU信息')),
                ('disk', models.CharField(blank=True, max_length=32, null=True, verbose_name='硬盘')),
                ('memory', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存')),
                ('hostname', models.CharField(blank=True, max_length=32, null=True, verbose_name='主机名')),
                ('mac', models.CharField(blank=True, max_length=32, null=True, verbose_name='MAC地址')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Server',
            },
        ),
    ]
