# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='标记'),
        ),
    ]
